workers_in_pool: 6
# The number of records to process in a batch.
batch_size: 10

data_start_pos: 0
data_end_pos: 1000

target_section:
  findings: true
  impression: true
  provisional_findings_impression: true
  findings_and_impression: true
