corenlp:
  #?properties={"annotators":"coref","coref.algorithm":"statistical","outputFormat":"json"}
  request_url: 'http://0.0.0.0:8802/' 

  server:
    memory: 8G
    threads: 14
    endpoint: http://localhost:8802
    outputFormat: json
    be_quiet: True
    timeout: 600000 # milliseconds. 60000ms would not be enough for batch_size = 10

  server_properties:
    scoref:
      annotators: tokenize, ssplit, pos, lemma, ner, depparse, coref
      coref_algorithm: statistical
    ncoref:
      annotators: tokenize, ssplit, pos, lemma, ner, parse, coref
      coref_algorithm: neural
    dcoref:
      annotators: tokenize, ssplit, pos, lemma, ner, parse, dcoref