voting:
  prefix: "[mv]"
  column_name:
    # "token" and "sentence_group" columns are directly copied from spacy

    coref_group: ${name_style.voting.prefix}coref_group
    coref_group_conll: ${name_style.voting.prefix}coref_group_conll

    tok_vote: ${name_style.voting.prefix}tok_vote
    tok_vote_count: ${name_style.voting.prefix}tok_vote_count
    mention: ${name_style.voting.prefix}mention
    mention_confidence: ${name_style.voting.prefix}mention_confidence
    mention_pair: ${name_style.voting.prefix}mention_pair
    mention_pair_vote: ${name_style.voting.prefix}mention_pair_vote
    mention_pair_vote_count: ${name_style.voting.prefix}mention_pair_vote_count

