# If use a relative path, it will base on the path that we execute the python command.
work_dir: ${machine.work_dir}
src_dir: ${work_dir}/src
output_dir: ${work_dir}/output
log_dir: ${work_dir}/logs/${hydra.job.config_name}
logging_level: INFO # DEBUG, INFO

ignore_source_path: ${work_dir}/config/ignore/common_ignore

fast_coref_dir: ${machine.fast_coref_dir}
coref_scorer_dir: ${machine.fast_coref_dir}/coref_resources/reference-coreference-scorers # This is the scorer for CoNLL-2011/2012 shared tasks on coreference resolution

defaults:
  - hydra/custom_logging
  - machine: arcca
  - _self_