defaults:
  - common
  - coref_data_preprocessing/i2b2
  - coref_data_preprocessing/mimic_cxr
  - name_style/mimic_cxr_sections
  - name_style/corenlp_output
  - name_style/spacy_output
  - nlp_properties/corenlp
  - coref/ensemble
  - _self_

module_dir_name: coreference_resolution