# The config is in the files under the graph_annotation_process/ folder


defaults:
  - common
  # The correct config file will be chosen in scripts. No need to modify here.
  - graph_annotation_process@_global_: radgraph_to_brat