defaults:
  - common
  - name_style/corenlp_output
  - name_style/spacy_output
  - name_style/fastcoref_joint_output
  - nlp_properties/spacy
  - nlp_properties/corenlp
  - linguistic_preprocessing@_global_: mimic_cxr # The correct config file be chosen in the scripts. No need to modify here.
  - _self_

# This is the alignment base. It means that any model/library/tool outputs are aligned to the spaCy outputs (tokens).
spacy:
  output_dir: ${output.base_dir}/spacy
  activate: false
  multiprocess_workers: 15

corenlp:
  output_dir: ${output.base_dir}/corenlp
  activate: false
  multiprocess_workers: 14 # For i2b2, it will be force set to 1 automatically
  use_server_properties: # At least one should be true
    scoref: true # Containing the statistical (ML-based) coref annotator.
    dcoref: true # Containing the deterministic (Rule-based) coref annotator.
    ncoref: false # Containing the neural coref annotator
  unfinished_records_path: ${corenlp.output_dir}/corenlp_unfinished_records.log
  uncompleted_dependency_parsing_records: ${corenlp.output_dir}/corenlp_uncompleted_dependency_parsing_records.log

corenlp_for_unfinished_records:
  activate: false
  multiprocess_workers: 1
  max_iteration_num: 2 # How many times to re-activate the corenlp
  unfinished_records_path: ${corenlp.unfinished_records_path}

fastcoref_joint:
  output_dir: ${output.base_dir}/fast_coref_onto_i2b2
  activate: true
  model_dir: ${fast_coref_dir}/models/coref_joint_train_onto_i2b2_301
  doc_encoder_dir: ${fast_coref_dir}/models/longformer_coreference_joint
  unfinished_records_path: ${fastcoref_joint.output_dir}/fastcoref_unfinished_records.log

metamap: 
  activate: false

stanza:
  activate: false
