input:
  path: ${output_dir}/mimic_cxr_sections.jsonlines

clear_history: true

output:
  base_dir: ${output_dir}/nlp_ensemble
  log_file: run.log

  section:
    findings: true
    impression: true
    provisional_findings_impression: true
    findings_and_impression: true

batch_process:
  data_start_pos: 0
  data_end_pos: 20
  batch_size: 5


# This is the alignment base. It means that any model/library/tool outputs are aligned to the spaCy outputs (tokens).
spacy:
  output_dir: ${output.base_dir}/spacy
  # Spacy is always activated
  activate: true
  # load_previous: false # If True, we don't process the raw data from scratch but load from the previously saved outputs e.g. the CSV files in ${output_dir}.
  multiprocess_workers: 15

corenlp:
  output_dir: ${output.base_dir}/corenlp
  activate: true
  multiprocess_workers: 14
  use_server_properties: # At least one should be true
    scoref: true # Containing the statistical (ML-based) coref annotator.
    dcoref: true # Containing the deterministic (Rule-based) coref annotator.
    ncoref: false # Containing the neural coref annotator
  unfinished_records_path: ${corenlp.output_dir}/corenlp_unfinished_records.log

corenlp_for_unfinished_records:
  activate: false
  multiprocess_workers: 10
  unfinished_records_path: ${corenlp.unfinished_records_path}

fastcoref_joint:
  output_dir: ${output.base_dir}/fast_coref_joint
  activate: false
  model_dir: ${fast_coref_dir}/models/joint_best
  doc_encoder_dir: ${fast_coref_dir}/models/longformer_coreference_joint
  unfinished_records_path: ${fastcoref_joint.output_dir}/fastcoref_unfinished_records.log

metamap: 
  activate: false

stanza:
  activate: false


defaults:
  - common
  - name_style/mimic_cxr_sections
  - name_style/corenlp_output
  - name_style/spacy_output
  - name_style/fastcoref_joint_output
  - nlp_properties/spacy
  - nlp_properties/corenlp
  - _self_
