thread:
  workers: 15

defaults:
  - common
  - name_style/corenlp_output
  - name_style/spacy_output
  - name_style/fastcoref_joint_output
  - name_style/scoring_output
  - _self_

# Append the necessary config group via command line:
# e.g. sys.argv.append("+statistic/alignment@_global_=i2b2")