# Should not contain space symbol in the path.
dataset_dir: /Users/liao/Desktop/DBMI_c2b2_2011_coref
output_dir: /Users/liao/Desktop/i2b2
# 0 to use random seed to shuffle the dataset; -1 to disable the shuffle; Or any int value as static seed.
shuffle_seed: 0
# In safe mode, the conflict dirs during the raw2conll processing need to be removed manually.
safe_mode: false

defaults:
  - common
  - hydra/custom_logging
  - _self_

###
# Users don't have to modify the below configs
###
output:
  root_dir_name: conll
  temp_dir_name: temp
  suffix: .conll

input:
  chain_suffix: .chains
  doc_dir_name: docs
  chain_dir_name: chains
  

data_split:
  # Will be used when either ${data_split.cross_validation} or ${data_split.random_shuffle} is true, as files need to be *split*.
  if_split:
    output_name_prefix: train,dev,test # Should match to the length of ${data_split.proportion}
    proportion: 7,2,1 # In which proportion to split the source files.
  # It will create datasets for 10-folds cross-validation. The source files will be *split*.
  # The source files will be shuffled after spliting the tran+dev and test sets, which means the test set of each fold will not overlap.
  cross_validation: true
  if_cross_validation:
    folds: 10 # The dir_name will be the index of the folds
  # It will create a dataset that shuffle the source files. The source files will be *split*.
  random_shuffle: true
  if_random_shuffle:
    dir_name: random
  # It will only create one file with prefix "all" without spliting the source files. The source files will NOT be *split*.
  unsplit: true
  if_unsplit:
    dir_name: all
    output_name_prefix: all

paths:
  beth_train: ${dataset_dir}/Beth_Train
  beth_test: ${dataset_dir}/i2b2_Test/i2b2_Beth_Test
  beth_test_ground_truth: ${dataset_dir}/Tack_1C_to_be_released_10_02_2011/i2b2_Beth_Test
  partners_train: ${dataset_dir}/Partners_Train
  partners_test: ${dataset_dir}/i2b2_Test/i2b2_Partners_Test
  partners_test_ground_truth: ${dataset_dir}/Tack_1C_to_be_released_10_02_2011/i2b2_Partners_Test
