resource_paths:
  root: ${src_dir}/${module_dir_name}/resources
  heading_affiliation_map: ${data_preprocessing.resource_paths.root}/HeadingAffiliationMapping_slim.txt
  technique_procedureinfo: ${data_preprocessing.resource_paths.root}/Technique_ProcedureInfo.txt
  ignore_heading: ${data_preprocessing.resource_paths.root}/IgnoreHeading.txt
  manually_processed_records: ${data_preprocessing.resource_paths.root}/manually_processed_records.json