# Generate ann files for annotation in the brat server
input:
  base_dir: ${resource_dir}/radgraph
  train_file: ${input.base_dir}/train.json
  dev_file: ${input.base_dir}/dev.json
  test_file: ${input.base_dir}/test.json

output:
  base_dir: ${base_output_dir}/radgraph
  for_inspection_dir: ${output.base_dir}/originalData_bratFormatted
  for_ann_dir: ${output.base_dir}/brat_data_for_annotation
